const Discord = require('discord.js')

module.exports.run = async (bot, message, args) => {

    let helpEmbed = new Discord.RichEmbed()
        .setColor(0xeded21)
        .setTitle('Command Help')
        .setDescription('**Do `b!help [command]` to see info for the command!**')
        .addField('🎲 Random Outcomes', '`8ball`, `dice`')
        .addField('🌎 Internet', '`google` (soon)')
        .addField('⚙️ Server Options', '`purge`')
        .addField('🎚️ Moderating', '`kick`, `ban`')
        .setFooter('Generated by BotPor')

        message.reply('check your DMs!')
    message.author.send(helpEmbed)
    if (['8ball', '8', 'ball', '8b'].includes(args[1]))
        message.channel.send('**8ball:** Ask the 8ball something! (Disclaimer: The 8ball does not predict the future.)\nUsage: `b!8ball [question]`\nExample: `b!8ball Will I win a marathon?`\n\nAliases: 8, ball, 8b')
    if (['dice', 'die', 'd'].includes(args[1]))
        message.channel.send('**Dice:** Gives you a random number from a die!\nUsage: `b!dice`\n\nAliases: die, d')
}

module.exports.help = {
    name: "help",
    aliases: []
}