const Discord = require('discord.js')

module.exports.run = async (bot, message, args) => {
    let inviteEmbed = new Discord.RichEmbed()
        .setColor(0xeded21)
        .setDescription('**Click [here](http://bit.ly/addbotpor) to invite me to your server!**')
        .setFooter('Generated by BotPor')

        message.reply('check your DMs!')
    message.author.send(inviteEmbed)
}

module.exports.help = {
    name: "invite",
    aliases: ["joinbot"]
}